"""
Reporter.
 
Produces a self-contained HTML analytics report: executive narrative,
interactive Plotly charts, a data table, and the SQL that produced the
results. LLM (Groq) generates the SQL/narrative/chart spec in one call.
"""
import json
import re
from pathlib import Path
 
import duckdb
import plotly.graph_objects as go
 
from core.config import REPORTS_DIR
from core.audit import AuditLogger
from core.llm import call_llm
 
HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Report - {run_id}</title>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
<style>
body {{ font-family: Arial, sans-serif; max-width: 1100px; margin: 40px auto; padding: 0 24px; color: #1a1a2e; }}
h1 {{ color: #1565C0; border-bottom: 2px solid #1565C0; padding-bottom: 8px; }}
h2 {{ color: #1565C0; margin-top: 36px; }}
.narrative {{ background: #f0f5ff; border-left: 4px solid #1565C0; padding: 16px 20px; border-radius: 4px; line-height: 1.7; white-space: pre-wrap; }}
.data-table {{ border-collapse: collapse; width: 100%; margin-top: 12px; font-size: 13px; }}
.data-table th {{ background: #1565C0; color: white; padding: 8px 12px; text-align: left; }}
.data-table td {{ padding: 7px 12px; border-bottom: 1px solid #e0e0e0; }}
.data-table tr:nth-child(even) {{ background: #f5f7fa; }}
.chart-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(480px, 1fr)); gap: 24px; margin-top: 16px; }}
.chart-box {{ border: 1px solid #e0e0e0; border-radius: 8px; padding: 16px; background: #ffffff; }}
footer {{ margin-top: 48px; font-size: 12px; color: #999; text-align: center; border-top: 1px solid #e0e0e0; padding-top: 16px; }}
</style>
</head>
<body>
<h1>Business Intelligence Report</h1>
<p><strong>Run ID:</strong> {run_id}</p>
<p><strong>Business Intent:</strong> {business_intent}</p>
<h2>Executive Summary</h2>
<div class="narrative">{narrative}</div>
<h2>Data Results</h2>
{table_html}
<h2>Visual Analysis</h2>
<div class="chart-grid">
{chart_divs}
</div>
<footer>Generated by Agentic Medallion Pipeline &middot; Run {run_id}</footer>
</body>
</html>
"""
 
 
def _extract_sql(text: str) -> str:
    match = re.search(r"```sql\s*(.*?)```", text, re.DOTALL | re.IGNORECASE)
    if match:
        return match.group(1).strip()
    match = re.search(r"(SELECT\s+.+?;)", text, re.DOTALL | re.IGNORECASE)
    return match.group(1).strip() if match else ""
 
 
# Matches "SQL:", "**SQL**", "SQL", "## SQL" etc. as section headers, so
# formatting drift from the model (colon vs. bold vs. markdown heading)
# doesn't cause the whole section to be missed.
def _section_span(text: str, label: str):
    pattern = rf"(?:^|\n)\s*[#*]*\s*{label}\s*[:*]*\s*(?:\n|$)"
    match = re.search(pattern, text, re.IGNORECASE)
    return match.end() if match else None
 
 
def _extract_narrative(text: str) -> str:
    start = _section_span(text, "NARRATIVE")
    if start is None:
        # fallback: if no NARRATIVE header at all, treat any prose outside
        # code fences and outside SQL/CHARTS headers as the narrative
        stripped = re.sub(r"```.*?```", "", text, flags=re.DOTALL)
        stripped = re.sub(
            r"(?:^|\n)\s*[#*]*\s*(SQL|CHARTS)\s*[:*]*\s*(?:\n|$)",
            "\n", stripped, flags=re.IGNORECASE,
        )
        return stripped.strip()
 
    next_header = re.search(
        r"(?:^|\n)\s*[#*]*\s*(?:SQL|CHARTS)\s*[:*]*\s*(?:\n|$)",
        text[start:], re.IGNORECASE,
    )
    end = start + next_header.start() if next_header else len(text)
    return text[start:end].strip()
 
 
def _extract_json_block(text: str) -> list:
    # 1. Preferred: CHARTS section (colon or bold header) followed by a fence
    match = re.search(
        r"(?:^|\n)\s*[#*]*\s*CHARTS\s*[:*]*\s*(?:\n|.)*?```json\s*(.*?)```",
        text, re.DOTALL | re.IGNORECASE,
    )
    candidate = match.group(1) if match else None
 
    # 2. Fallback: any fenced block that looks like a JSON array
    if candidate is None:
        for m in re.finditer(r"```(?:json)?\s*(\[.*?\])\s*```", text, re.DOTALL | re.IGNORECASE):
            candidate = m.group(1)
            break
 
    # 3. Fallback: a bare [...] array anywhere in the text, not in a fence
    if candidate is None:
        m = re.search(r"(\[\s*\{.*?\}\s*\])", text, re.DOTALL)
        if m:
            candidate = m.group(1)
 
    if candidate is None:
        return []
 
    try:
        data = json.loads(candidate)
        return [
            spec for spec in data
            if isinstance(spec, dict) and all(k in spec for k in ("type", "x", "y", "title"))
        ]
    except Exception:
        return []
 
 
def _resolve_column(name: str, columns) -> str | None:
    """Case/whitespace-insensitive match of a requested column name against
    the actual DataFrame columns, so minor casing differences from the LLM
    don't silently drop an otherwise-valid chart."""
    if name in columns:
        return name
    lowered = {c.lower().strip(): c for c in columns}
    return lowered.get(str(name).lower().strip())
 
 
def _fallback_chart(result_df):
    """If the LLM produced no usable chart spec, build one sensible chart
    directly from the result data so the report is never empty-handed:
    first non-numeric column as the category axis, first numeric column
    as the value axis."""
    import pandas as pd
    numeric_cols = [c for c in result_df.columns if pd.api.types.is_numeric_dtype(result_df[c])]
    non_numeric_cols = [c for c in result_df.columns if c not in numeric_cols]
    if not numeric_cols or not non_numeric_cols:
        return None
    x, y = non_numeric_cols[0], numeric_cols[0]
    try:
        x_vals = result_df[x].astype(str).tolist()
        y_vals = [float(v) for v in result_df[y]]
        fig = go.Figure(data=[go.Bar(x=x_vals, y=y_vals)])
        fig.update_layout(
            title=f"{y} by {x}",
            template="plotly_white",
            font=dict(family="Arial", size=13),
            margin=dict(t=50, b=40, l=40, r=40),
        )
        fig.update_xaxes(title_text=x)
        fig.update_yaxes(title_text=y)
        return fig.to_html(full_html=False, include_plotlyjs=False)
    except Exception:
        return None
 
 
def generate_report(gold_paths: list[str], business_intent: str, run_id: str) -> str:
    audit = AuditLogger(run_id)
    try:
        con = duckdb.connect()
        table_names = []
        for path in gold_paths:
            table_name = Path(path).stem
            con.execute(f"CREATE VIEW {table_name} AS SELECT * FROM read_parquet('{path}')")
            table_names.append(table_name)
        first_gold_table = table_names[0]
 
        schema_blocks = []
        for table_name in table_names:
            columns_df = con.execute(f"DESCRIBE {table_name}").df()
            preview_df = con.execute(f"SELECT * FROM {table_name} LIMIT 5").df()
            schema_blocks.append(
                f"Table: {table_name}\nColumns: {columns_df['column_name'].tolist()}\n"
                f"Preview:\n{preview_df.to_string(index=False)}"
            )
 
        prompt = (
            f"Business intent: {business_intent}\n\n"
            + "\n\n".join(schema_blocks)
            + "\n\nOutput exactly three labeled sections in this order:\n"
            "SQL: (a single DuckDB-compatible SELECT statement answering the "
            "business question, wrapped in a ```sql fence)\n"
            "NARRATIVE: (2-3 paragraph executive summary in plain English, "
            "highlighting key trends, top performers, and business implications)\n"
            "CHARTS: (a JSON array of chart specs, each with keys: type, x, y, "
            "title, wrapped in a ```json fence)\n"
            "Column names must exactly match those shown in the preview."
        )
 
        llm_text = call_llm(prompt, max_tokens=3000)
 
        sql = _extract_sql(llm_text)
        narrative = _extract_narrative(llm_text)
        chart_specs = _extract_json_block(llm_text)
 
        try:
            if sql:
                result_df = con.execute(sql).df()
            else:
                raise ValueError("no SQL extracted")
        except Exception:
            result_df = con.execute(f"SELECT * FROM {first_gold_table} LIMIT 20").df()
 
        chart_htmls = []
        for spec in chart_specs:
            try:
                x_col = _resolve_column(spec["x"], result_df.columns)
                y_col = _resolve_column(spec["y"], result_df.columns)
                if x_col is None or y_col is None:
                    continue
                # Use graph_objects with explicit plain-list conversion
                # rather than plotly.express -- px converts through
                # pandas/numpy internally regardless of input type, which
                # triggers Plotly's compact base64 typed-array encoding
                # ("bdata"). That encoding needs a closely-matched
                # plotly.js version to decode correctly; a slightly stale
                # CDN-cached copy can silently misrender bar heights while
                # labels/titles still look fine. Plain Python lists never
                # trigger that encoding, so the chart renders correctly
                # regardless of which plotly.js version the browser loads.
                x_vals = result_df[x_col].astype(str).tolist()
                y_vals = [float(v) for v in result_df[y_col]]
                if spec["type"] == "bar":
                    fig = go.Figure(data=[go.Bar(x=x_vals, y=y_vals)])
                elif spec["type"] == "pie":
                    fig = go.Figure(data=[go.Pie(labels=x_vals, values=y_vals)])
                elif spec["type"] == "line":
                    fig = go.Figure(data=[go.Scatter(x=x_vals, y=y_vals, mode="lines+markers")])
                else:
                    continue
                fig.update_layout(
                    title=spec["title"],
                    template="plotly_white",
                    font=dict(family="Arial", size=13),
                    margin=dict(t=50, b=40, l=40, r=40),
                )
                if spec["type"] != "pie":
                    fig.update_xaxes(title_text=x_col)
                    fig.update_yaxes(title_text=y_col)
                chart_htmls.append(fig.to_html(full_html=False, include_plotlyjs=False))
            except Exception:
                continue
 
        # Guarantee at least one visual: if the LLM's chart specs didn't
        # produce anything usable, build a sensible chart directly from
        # the result data instead of showing an empty section.
        if not chart_htmls:
            fallback = _fallback_chart(result_df)
            if fallback:
                chart_htmls.append(fallback)
            else:
                debug_path = REPORTS_DIR / f"report_{run_id[:8]}.raw_llm_response.txt"
                debug_path.write_text(llm_text, encoding="utf-8")
                audit.log(
                    "reporter",
                    "no_charts_generated",
                    raw_response_saved_to=str(debug_path),
                )
 
        table_html = result_df.to_html(index=False, classes="data-table", border=0, na_rep="---")
        chart_divs = "\n".join(f'<div class="chart-box">{c}</div>' for c in chart_htmls)
 
        html = HTML_TEMPLATE.format(
            run_id=run_id,
            business_intent=business_intent,
            narrative=narrative or "No narrative generated.",
            table_html=table_html,
            chart_divs=chart_divs or "<p>No charts generated.</p>",
        )
 
        out_path = REPORTS_DIR / f"report_{run_id[:8]}.html"
        out_path.write_text(html, encoding="utf-8")
        audit.log("reporter", "report_generated", output_path=str(out_path))
        return str(out_path)
 
    except Exception as e:
        audit.log("reporter", "report_generation_failed", error=str(e))
        out_path = REPORTS_DIR / f"report_{run_id[:8]}.html"
        out_path.write_text(
            f"<html><body><h1>Report Generation Error</h1><p>{e}</p></body></html>",
            encoding="utf-8",
        )
        return str(out_path)